? ''
: - {type: A, value: 69.200.236.17}
  - ttl: 86400
    type: MX
    values:
    - {exchange: mx.zoho.com., preference: 10}
    - {exchange: mx2.zoho.com., preference: 20}
  - {ttl: 86400, type: SPF, value: 'v=spf1 mx include:zoho.com ~all'}
  - {ttl: 86400, type: TXT, value: keybase-site-verification=QhdmHUpLYp6nSAh5acpWGnHBLYtHRE5JCQGrerXIImI}
_amazonses: {ttl: 86400, type: TXT, value: nOSqNz6GuHWUV/GdUWiXEWRTTRMK/ibv6afYRtn5WtU=}
a: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
b: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
c: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
d: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
deluge: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
e: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
ec25ukpzz6h4nddab3jyevcnzmmmbrgm._domainkey: {ttl: 86400, type: CNAME, value: ec25ukpzz6h4nddab3jyevcnzmmmbrgm.dkim.amazonses.com.}
erlite: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
f: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
freenas: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
g: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
gc4caluqqezmfk6xanwpdpw5eytglrkn._domainkey: {ttl: 86400, type: CNAME, value: gc4caluqqezmfk6xanwpdpw5eytglrkn.dkim.amazonses.com.}
h: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
hypnotoad: {ttl: 604800, type: CNAME, value: hypnotoad.desertbluffs.com.s3-website-us-east-1.amazonaws.com.}
i: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
j: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
jenkins: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
k: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
l: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
m: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
n: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
nzbget: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
o: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
p: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
plex: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
plexpy: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
ptusb247sybmwk4i32j5lmagtmtqq7qi._domainkey: {ttl: 86400, type: CNAME, value: ptusb247sybmwk4i32j5lmagtmtqq7qi.dkim.amazonses.com.}
q: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
r: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
radarr: {ttl: 300, type: CNAME, value: desertbluffs.com.}
s: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
smokeping: {ttl: 300, type: CNAME, value: desertbluffs.com.}
sonarr: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
syncthing: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
t: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
u: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
unifi: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
v: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
w: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
x: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
y: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
z: {ttl: 604800, type: CNAME, value: desertbluffs.com.}
zb14086362: {ttl: 300, type: CNAME, value: zmverify.zoho.com.}
